name: geo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy=2.2.*
  - pandas=2.3.2
  - pyarrow=21.0.0
  - numexpr=2.10.*
  - bottleneck=1.4.2
  - geopandas=1.1.1
  - rasterio=1.4.3
  - pyproj=3.7.1
  - shapely=2.1.1
  - fiona=1.10.1
  - gdal=3.10.3
  - jupyterlab=4.4.5
  - seaborn=0.13.2
  - matplotlib=3.10.5
  - statsmodels=0.14.5
  - scipy=1.16.1
  - scikit-learn=1.7.2
  - rtree=1.4.1
  - numba=0.61.2
  - spreg=1.8.3
  - esda=2.7.1
  - libpysal=4.13.0
  - splot=1.1.7
  - pip=25.2
  - pip:
    - streamlit==1.49.1
    - streamlit-folium==0.25.3
    - folium==0.20.0
